language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

install: 
    - pip install -r requirements/requirements.txt
    - pip install -r requirements/dev-requirements.txt

script: 
    - pytest

after_success:
    coveralls
